version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # ports:
    #   - '5464:5432'
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true # for biding.pry
    tty: true # for biding.pry
    volumes:
      - .:/gpt_homepage_creator
    ports:
      - "0.0.0.0:3011:3000"
      # - "3011:3000"
    depends_on:
      - db
  redis:
    image: redis
    command: redis-server --appendonly yes
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/gpt_homepage_creator
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379