version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # ports:
    #   - '5464:5432'
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec rails assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/gpt_homepage_creator
    # ports:
    #   - "3011:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
  redis:
    image: redis
    command: redis-server --appendonly yes
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/gpt_homepage_creator
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  nginx:
    container_name: gpt_homepage_creator_nginx
    build: docker/nginx/
    volumes:
      - ./run/:/var/run/